### ISSUE TITLE
Any plan for presenting a survey?

### ISSUE THREAD

**Issue by BUAADreamer** [haokunwen/Awesome-Composed-Image-Retrieval#2]

**Comment by haokunwen** [comment]
Hi~ Our team is working on it.  Please stay tuned.

**Comment by BIGBALLON** [comment]
Perhaps you could add another category for retrieval models **based on MLLM(multimodal large models).** This direction has gained popularity after 2024, with a steady stream of work emerging in this area.

- E5-V: Universal Embeddings with Multimodal Large Language Models
- VLM2Vec: Training Vision-Language Models for Massive Multimodal Embedding Tasks
- MM-Embed: Universal Multimodal Retrieval with Multimodal LLMs
- LamRA: Large Multimodal Model as Your Advanced Retrieval Assistant
- GME: Improving Universal Multimodal Retrieval by Multimodal LLMs


BTW，The performance of [GME](https://github.com/BIGBALLON/GME-Search) is really impressive.  check https://github.com/BIGBALLON/GME-Search for more details.

**Comment by BIGBALLON** [comment]
Additionally, in my personal opinion, composed image retrieval might become a subfield for solving the problem of universal embedding in the future(from GME).

**Comment by haokunwen** [comment]
Many thanks for your invaluable suggestions! I wholeheartedly concur with you that universal multimodal retrieval/embedding is the way forward, and CIR is just a subset of it. The related work you've listed above indeed falls into a more comprehensive category of CIR. We will seriously take your kind advice into account :)

**Comment by BIGBALLON** [comment]
[Update]

A new paper list with UME(Universal Multimodal Embedding): https://github.com/BIGBALLON/UME-Search
and a new post [Beyond CLIP：Toward Universal Multimodal Embedding](https://zhuanlan.zhihu.com/p/1933650595606148849)
