### ISSUE TITLE
MagicLens should be zero-shot CIR

### ISSUE THREAD

**Issue by drogozhang** [haokunwen/Awesome-Composed-Image-Retrieval#4]
Hi, thanks for the great paper list!

I think MagicLens should be categorized into zero-shot CIR and it can also perform the sketch-based image retrieval according to the paper.

Thanks for your attention!

**Comment by haokunwen** [comment]
Hi~ Thank you for your kind remarks. I have classified MagicLens as zero-shot CIR for a more suitable categorization.

**Comment by YasmineXXX** [comment]
According to the definition of zero-shot compositional image retrieval, the training process should not utilize training samples. However, MagicLens employs paired information of queries and targets during training. Therefore, should it be classified as a supervised method? Looking forward to your response!
