### ISSUE TITLE
Good job 

### ISSUE THREAD

**Issue by KevinLight831** [haokunwen/Awesome-Composed-Image-Retrieval#5]
Thank you for sincerely answering my questions when I first entered this field and reached out to you via email. I never expected that you would continue to delve such deeply into this area over the past two years, accumulating such extensive knowledge and now preparing to compile it into a comprehensive survey to help more junior researchers. Well done and sincere respect.👍

**Comment by haokunwen** [comment]
Thank you very much for your kind words and recognition! I truly appreciate your encouragement :）
